version: '3'

services:
  drone:
    image: drone/drone:1.8.0
    ports:
      - "$DRONE_HTTP_PORT:80"
      - "$DRONE_HTTPS_PORT:443"
    environment:
      - DRONE_SERVER_HOST=${SERVER_IP}:${DRONE_HTTP_PORT}
      - DRONE_GITEA_SERVER=http://${SERVER_IP}:${GITEA_WEB_PORT}
    env_file:
      - .drone.env
      - .rpc.env
      - .env
    restart: always

  runner:
    image: drone/drone-runner-docker:1.4.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .runner.env
      - .rpc.env
      - .env
    ports:
      - "$DRONE_RUNNER_PORT:3000"
    restart: always

  gitea:
    image: gitea/gitea:1.12.1
    ports:
      - "$GITEA_WEB_PORT:3000"
      - "$GITEA_SSH_PORT:22"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      - DB_TYPE=sqlite3
      - DOMAIN=$SERVER_IP
      - SSH_DOMAIN=$SERVER_IP
      - SSH_PORT=$GITEA_SSH_PORT
      - SSH_LISTEN_PORT=22
      - ROOT_URL=$GITEA_WEB_URL
    env_file:
      - .env